# Generated by Django 5.1.7 on 2025-05-18 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcement_images')),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='brochures/')),
                ('year', models.IntegerField(default=2024)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='downloads')),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='reports/')),
                ('year', models.IntegerField(default=2024)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('requested_role', models.CharField(default='Slot Coordinator', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('location', models.CharField(editable=False, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='camp_images/')),
                ('total_students', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'state', 'city'],
                'indexes': [models.Index(fields=['city'], name='api_camp_city_6bd212_idx'), models.Index(fields=['state'], name='api_camp_state_40da64_idx'), models.Index(fields=['year'], name='api_camp_year_3d13c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('entry_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('webmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('role', models.CharField(choices=[('Coordinator', 'Coordinator'), ('Slot Coordinator', 'Slot Coordinator'), ('Admin', 'Admin')], default='Slot Coordinator', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to=settings.AUTH_USER_MODEL)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='api.camp')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(db_index=True, editable=False, max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('regularclasses', 'Regular Classes'), ('doubts', 'Doubts'), ('exams', 'Exams')], default='regularclasses', max_length=20)),
                ('year', models.IntegerField(editable=False)),
                ('student_count', models.PositiveIntegerField(default=0, editable=False)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.camp')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['location'], name='api_gallery_locatio_dfcab9_idx'), models.Index(fields=['type'], name='api_gallery_type_f7d846_idx'), models.Index(fields=['year'], name='api_gallery_year_c2e9fe_idx'), models.Index(fields=['date'], name='api_gallery_date_4c95ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='student_avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('standard', models.CharField(choices=[('Nursery', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11 (M)', '11 (M)'), ('11 (B)', '11 (B)'), ('12 (M)', '12 (M)'), ('12 (B)', '12 (B)'), ('Dropper', 'Dropper')], db_index=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('school_name', models.CharField(db_index=True, max_length=200)),
                ('father_name', models.CharField(db_index=True, max_length=200)),
                ('father_occupation', models.CharField(db_index=True, max_length=200)),
                ('father_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('mother_name', models.CharField(db_index=True, max_length=200)),
                ('mother_occupation', models.CharField(db_index=True, max_length=200)),
                ('mother_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('principal_name', models.CharField(db_index=True, max_length=200)),
                ('principal_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.camp')),
            ],
            options={
                'ordering': ['standard', 'name'],
                'indexes': [models.Index(fields=['name'], name='api_student_name_0a5381_idx'), models.Index(fields=['registration_date'], name='api_student_registr_ca8128_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='test_papers/')),
                ('exam_date', models.DateField()),
                ('type', models.CharField(choices=[('screening', 'Screening Test Paper'), ('surprise', 'Surprise Test Paper'), ('weekly', 'Weekly Test Paper')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('standard', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_papers', to='api.camp')),
            ],
            options={
                'verbose_name': 'Test Paper',
                'verbose_name_plural': 'Test Papers',
                'ordering': ['-exam_date', '-created_at'],
                'indexes': [models.Index(fields=['type'], name='api_testpap_type_897adf_idx'), models.Index(fields=['exam_date'], name='api_testpap_exam_da_1a6c49_idx'), models.Index(fields=['standard'], name='api_testpap_standar_8ed8f8_idx'), models.Index(fields=['created_at'], name='api_testpap_created_5e5b43_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='test_results/')),
                ('result_date', models.DateField()),
                ('type', models.CharField(choices=[('screening', 'Screening Test Result'), ('surprise', 'Surprise Test Result'), ('weekly', 'Weekly Test Result')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('standard', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='api.camp')),
            ],
            options={
                'verbose_name': 'Test Result',
                'verbose_name_plural': 'Test Results',
                'ordering': ['-result_date', '-created_at'],
                'indexes': [models.Index(fields=['type'], name='api_testres_type_36ab93_idx'), models.Index(fields=['result_date'], name='api_testres_result__b0c641_idx'), models.Index(fields=['standard'], name='api_testres_standar_66bf01_idx'), models.Index(fields=['created_at'], name='api_testres_created_b15781_idx')],
            },
        ),
    ]
