# Generated by Django 5.1.7 on 2025-03-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='entry_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
